### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [transomjs/transom-ejs-template#1]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by transomjs** [comment]
EJS performance isn't a real problem for us and it has a relative file-based "include" operator that is not provided by template literals. If you have a need for something faster, I'd be happy to review a custom module for TransomJS.
